ALFRED_AFFORDANCE_LIST = [
    'Navigate',
    'PickupObject',
    'PutObject',
    'CleanObject',
    'HeatObject',
    'CoolObject',
    'ToggleObject',
    'SliceObject',
    'OpenObject',
]

ALFRED_INTEREST_OBJECTS = [
    'AlarmClock',
    'Apple',
    'AppleSliced',
    'ArmChair',
    'BaseballBat',
    'BasketBall',
    'BathtubBasin',
    'Bed',
    'Book',
    'Bowl',
    'Box',
    'Bread',
    'BreadSliced',
    'ButterKnife',
    'CD',
    'Cabinet',
    'Candle',
    'Cart',
    'CellPhone',
    'Cloth',
    'CoffeeMachine',
    'CoffeeTable',
    'CounterTop',
    'CreditCard',
    'Cup',
    'Desk',
    'DeskLamp',
    'DiningTable',
    'DishSponge',
    'Drawer',
    'Dresser',
    'Egg',
    'Faucet',
    'FloorLamp',
    'Fork',
    'Fridge',
    'GarbageCan',
    'Glassbottle',
    'HandTowel',
    'Kettle',
    'KeyChain',
    'Knife',
    'Ladle',
    'Laptop',
    'Lettuce',
    'LettuceSliced', 
    'Microwave',
    'Mug',
    'Newspaper',
    'Ottoman',
    'Pan',
    'Pen',
    'Pencil',
    'PepperShaker',
    'Pillow',
    'Plate',
    'Plunger',
    'Pot',
    'Potato',
    'PotatoSliced', 
    'RemoteControl',
    'Safe',
    'SaltShaker',
    'Shelf',
    'SideTable',
    'SinkBasin',
    'SoapBar',
    'SoapBottle',
    'Sofa',
    'Spatula',
    'Spoon',
    'SprayBottle',
    'Statue',
    'StoveBurner',
    'TennisRacket',
    'TissueBox',
    'Toilet',
    'ToiletPaper',
    'ToiletPaperHanger',
    'Tomato',
    'TomatoSliced',    
    'Vase',
    'Watch',
    'WateringCan',
    'WineBottle'
]





OBJECT_PROPS = {
    'AlarmClock'        :{'region':'point', 'min_expand':4 ,'max_expand':4, 'yaw_thresh':20},
    'Apple'             :{'region':'point', 'min_expand':4 ,'max_expand':4, 'yaw_thresh':20},
    'AppleSliced'       :{'region':'point', 'min_expand':4 ,'max_expand':4, 'yaw_thresh':20},
    'ArmChair'          :{'region':'area',  'min_expand':3 ,'max_expand':5, 'yaw_thresh':20},
    'BaseballBat'       :{'region':'point', 'min_expand':4 ,'max_expand':4, 'yaw_thresh':20},
    'BasketBall'        :{'region':'point', 'min_expand':4 ,'max_expand':4, 'yaw_thresh':20},
    'BathtubBasin'      :{'region':'area',  'min_expand':3 ,'max_expand':5, 'yaw_thresh':20},
    'Bed'               :{'region':'area',  'min_expand':3 ,'max_expand':5, 'yaw_thresh':20},
    'Book'              :{'region':'point', 'min_expand':4 ,'max_expand':4, 'yaw_thresh':20},
    'Bowl'              :{'region':'point', 'min_expand':4 ,'max_expand':4, 'yaw_thresh':20},
    'Box'               :{'region':'point', 'min_expand':4 ,'max_expand':4, 'yaw_thresh':20},
    'Bread'             :{'region':'point', 'min_expand':4 ,'max_expand':4, 'yaw_thresh':20},
    'BreadSliced'       :{'region':'point', 'min_expand':4 ,'max_expand':4, 'yaw_thresh':20},
    'ButterKnife'       :{'region':'point', 'min_expand':4 ,'max_expand':4, 'yaw_thresh':20},
    'CD'                :{'region':'point', 'min_expand':4 ,'max_expand':4, 'yaw_thresh':20},
    'Cabinet'           :{'region':'point', 'min_expand':4 ,'max_expand':4, 'yaw_thresh':20},
    'Candle'            :{'region':'point', 'min_expand':4 ,'max_expand':4, 'yaw_thresh':20},
    'Cart'              :{'region':'point', 'min_expand':4 ,'max_expand':4, 'yaw_thresh':20},
    'CellPhone'         :{'region':'point', 'min_expand':4 ,'max_expand':4, 'yaw_thresh':20},
    'Cloth'             :{'region':'point', 'min_expand':4 ,'max_expand':4, 'yaw_thresh':20},
    'CoffeeMachine'     :{'region':'point', 'min_expand':4 ,'max_expand':4, 'yaw_thresh':20},
    'CoffeeTable'       :{'region':'area',  'min_expand':3 ,'max_expand':5, 'yaw_thresh':20},
    'CounterTop'        :{'region':'area',  'min_expand':3 ,'max_expand':5, 'yaw_thresh':20},
    'CreditCard'        :{'region':'point', 'min_expand':4 ,'max_expand':4, 'yaw_thresh':20},
    'Cup'               :{'region':'point', 'min_expand':4 ,'max_expand':4, 'yaw_thresh':20},
    'Desk'              :{'region':'area',  'min_expand':3 ,'max_expand':5, 'yaw_thresh':20},
    'DeskLamp'          :{'region':'point', 'min_expand':4 ,'max_expand':4, 'yaw_thresh':0},
    'DiningTable'       :{'region':'area',  'min_expand':3 ,'max_expand':5, 'yaw_thresh':20},
    'DishSponge'        :{'region':'point', 'min_expand':4 ,'max_expand':4, 'yaw_thresh':20},
    'Drawer'            :{'region':'area',  'min_expand':3 ,'max_expand':5, 'yaw_thresh':20},
    'Dresser'           :{'region':'area',  'min_expand':3 ,'max_expand':5, 'yaw_thresh':20},
    'Egg'               :{'region':'point', 'min_expand':4 ,'max_expand':4, 'yaw_thresh':20},
    'Faucet'            :{'region':'point', 'min_expand':4 ,'max_expand':4, 'yaw_thresh':20},
    'FloorLamp'         :{'region':'point', 'min_expand':2 ,'max_expand':4, 'yaw_thresh':0},
    'Fork'              :{'region':'point', 'min_expand':4 ,'max_expand':4, 'yaw_thresh':20},
    'Fridge'            :{'region':'area',  'min_expand':4 ,'max_expand':4, 'yaw_thresh':20},       
    'GarbageCan'        :{'region':'point', 'min_expand':4 ,'max_expand':4, 'yaw_thresh':0},
    'Glassbottle'       :{'region':'point', 'min_expand':4 ,'max_expand':4, 'yaw_thresh':20},
    'HandTowel'         :{'region':'point', 'min_expand':4 ,'max_expand':4, 'yaw_thresh':20},
    'Kettle'            :{'region':'point', 'min_expand':4 ,'max_expand':4, 'yaw_thresh':20},
    'KeyChain'          :{'region':'point', 'min_expand':4 ,'max_expand':4, 'yaw_thresh':20},
    'Knife'             :{'region':'point', 'min_expand':4 ,'max_expand':4, 'yaw_thresh':20},
    'Ladle'             :{'region':'point', 'min_expand':4 ,'max_expand':4, 'yaw_thresh':20},
    'Laptop'            :{'region':'point', 'min_expand':4 ,'max_expand':4, 'yaw_thresh':20},
    'Lettuce'           :{'region':'point', 'min_expand':4 ,'max_expand':4, 'yaw_thresh':20},
    'LettuceSliced'     :{'region':'point', 'min_expand':4 ,'max_expand':4, 'yaw_thresh':20},
    'Microwave'         :{'region':'point', 'min_expand':4 ,'max_expand':4, 'yaw_thresh':0},
    'Mug'               :{'region':'point', 'min_expand':4 ,'max_expand':4, 'yaw_thresh':20},
    'Newspaper'         :{'region':'point', 'min_expand':4 ,'max_expand':4, 'yaw_thresh':20},
    'Ottoman'           :{'region':'point', 'min_expand':4 ,'max_expand':4, 'yaw_thresh':20},
    'Pan'               :{'region':'point', 'min_expand':4 ,'max_expand':4, 'yaw_thresh':20},
    'Pen'               :{'region':'point', 'min_expand':4 ,'max_expand':4, 'yaw_thresh':20},
    'Pencil'            :{'region':'point', 'min_expand':4 ,'max_expand':4, 'yaw_thresh':20},
    'PepperShaker'      :{'region':'point', 'min_expand':4 ,'max_expand':4, 'yaw_thresh':20},
    'Pillow'            :{'region':'point', 'min_expand':4 ,'max_expand':4, 'yaw_thresh':20},
    'Plate'             :{'region':'point', 'min_expand':4 ,'max_expand':4, 'yaw_thresh':20},
    'Plunger'           :{'region':'point', 'min_expand':4 ,'max_expand':4, 'yaw_thresh':20},
    'Pot'               :{'region':'point', 'min_expand':4 ,'max_expand':4, 'yaw_thresh':20},
    'Potato'            :{'region':'point', 'min_expand':4 ,'max_expand':4, 'yaw_thresh':20},
    'PotatoSliced'      :{'region':'point', 'min_expand':4 ,'max_expand':4, 'yaw_thresh':20},
    'RemoteControl'     :{'region':'point', 'min_expand':4 ,'max_expand':4, 'yaw_thresh':20},
    'Safe'              :{'region':'point', 'min_expand':4 ,'max_expand':4, 'yaw_thresh':20},
    'SaltShaker'        :{'region':'point', 'min_expand':4 ,'max_expand':4, 'yaw_thresh':20},
    'Shelf'             :{'region':'point', 'min_expand':4 ,'max_expand':4, 'yaw_thresh':20},
    'SideTable'         :{'region':'area',  'min_expand':3 ,'max_expand':5, 'yaw_thresh':20},
    'SinkBasin'         :{'region':'area',  'min_expand':3 ,'max_expand':5, 'yaw_thresh':20},
    'SoapBar'           :{'region':'point', 'min_expand':4 ,'max_expand':4, 'yaw_thresh':20},
    'SoapBottle'        :{'region':'point', 'min_expand':4 ,'max_expand':4, 'yaw_thresh':20},
    'Sofa'              :{'region':'area',  'min_expand':3 ,'max_expand':5, 'yaw_thresh':20},
    'Spatula'           :{'region':'point', 'min_expand':4 ,'max_expand':4, 'yaw_thresh':20},
    'Spoon'             :{'region':'point', 'min_expand':4 ,'max_expand':4, 'yaw_thresh':20},
    'SprayBottle'       :{'region':'point', 'min_expand':4 ,'max_expand':4, 'yaw_thresh':20},
    'Statue'            :{'region':'point', 'min_expand':4 ,'max_expand':4, 'yaw_thresh':20},
    'StoveBurner'       :{'region':'point', 'min_expand':4 ,'max_expand':4, 'yaw_thresh':20},
    'TennisRacket'      :{'region':'point', 'min_expand':4 ,'max_expand':4, 'yaw_thresh':20},
    'TissueBox'         :{'region':'point', 'min_expand':4 ,'max_expand':4, 'yaw_thresh':20},
    'Toilet'            :{'region':'point', 'min_expand':4 ,'max_expand':4, 'yaw_thresh':20},
    'ToiletPaper'       :{'region':'point', 'min_expand':4 ,'max_expand':4, 'yaw_thresh':20},
    'ToiletPaperHanger' :{'region':'point', 'min_expand':4 ,'max_expand':4, 'yaw_thresh':20},
    'Tomato'            :{'region':'point', 'min_expand':4 ,'max_expand':4, 'yaw_thresh':20},
    'TomatoSliced'      :{'region':'point', 'min_expand':4 ,'max_expand':4, 'yaw_thresh':20},
    'Vase'              :{'region':'point', 'min_expand':4 ,'max_expand':4, 'yaw_thresh':20},
    'Watch'             :{'region':'point', 'min_expand':4 ,'max_expand':4, 'yaw_thresh':20},
    'WateringCan'       :{'region':'point', 'min_expand':4 ,'max_expand':4, 'yaw_thresh':20},
    'WineBottle'        :{'region':'point', 'min_expand':4 ,'max_expand':4, 'yaw_thresh':20},
}
